import fs from 'fs';
import { interviewCategories } from './src/data/interviewData.js';

const sysDesignCategory = {
    id: "system-design-deep-dive",
    title: "System Design (Deep Dives)",
    questions: [
        {
            q: "Design a real-time fraud detection pipeline for a global payment processor (e.g., Stripe/Visa). It processes 50,000 transactions/sec, must evaluate ML models and block fraud in <50ms, and simultaneously sync data to a warehouse for offline training.",
            a: "This requires a highly decoupled, real-time event-driven architecture (Kappa or Lambda pattern) to handle the massive throughput and sub-50ms SLA.\n\n### 1. Ingestion Layer\n- **API Gateway -> Apache Kafka:** Incoming transactions hit the gateway and are published to a Kafka topic. \n- **Partitioning Strategy:** Partition by `Merchant_ID` or `User_ID` to ensure strict ordering of events per user and enable massive parallel consumption.\n\n### 2. Stream Processing (The 50ms SLA)\n- **Engine:** Use **Apache Flink** rather than Spark Streaming. Flink offers true event-by-event processing (microsecond latency) with advanced state management, whereas Spark uses micro-batching which struggles with strict sub-50ms SLAs.\n- **Feature Hydration:** Flink reads the raw transaction and queries a **Low-Latency Feature Store (Redis / ScyllaDB)** to pull historical aggregates (e.g., 'total spending in last 5 minutes', 'IP address risk score'). \n- **Inference:** Flink bundles the raw data and historical features, making a gRPC call to a served ML Model (e.g., via NVIDIA Triton or AWS SageMaker). Based on the score, Flink publishes a 'Block' or 'Allow' event to a downstream Kafka topic.\n\n### 3. State Management & Checkpointing\n- Flink maintains internal state (e.g., tumbling windows for 5-minute aggregates) using the **RocksDB State Backend**. It periodically checkpoints this state to S3/ADLS to ensure **Exactly-Once Processing** in case a worker node crashes.\n\n### 4. Offline Sync & Retraining\n- **Kafka Connect:** A sink connector asynchronously dumps the raw Kafka streams into an object store (S3) in Parquet format, orchestrated into an **Apache Iceberg or Delta Lake** table.\n- **Batch Jobs:** Daily Spark/dbt jobs compute complex features (e.g., '30-day average transaction value') and bulk-upsert them back into the Redis Feature Store for tomorrow's real-time inference.",
            complexity: "Complex"
        },
        {
            q: "Design a Machine Learning Feature Store platform (like Uber's Michelangelo). It must serve real-time features for inference at <10ms, while ensuring 'Point-in-Time Correctness' for offline model training to prevent data leakage.",
            a: "A Feature Store abstracts feature engineering from model deployment, providing a unified access layer for both training (offline) and inference (online).\n\n### 1. Dual-Storage Architecture\n- **Online Store (Redis / DynamoDB):** Optimized for low-latency row lookups by a primary key (e.g., `user_id = 123`). It stores *only the latest* feature values.\n- **Offline Store (Snowflake / Delta Lake):** Optimized for high-throughput batch scans. It acts as an append-only log, storing every historical change to a feature alongside a timestamp.\n\n### 2. Pipeline Design\n- **Batch Features:** Airflow schedules Spark jobs to compute heavy metrics (e.g., 'total rides last week'). It writes to the Offline Store, and a synchronization job (or reverse ETL) pushes the latest state to the Online Store.\n- **Streaming Features:** Flink consumes a Kafka event stream, calculates real-time windows (e.g., 'rides in last 5 mins'), and **dual-writes**: it updates the Online Store for instant serving and appends to the Offline Store for auditability.\n\n### 3. Solving Data Leakage (Point-in-Time Correctness)\n- **The Problem:** If a data scientist generates a training dataset for an event that happened at `t1`, but joins it with a feature value that was computed at `t2` (where `t2 > t1`), the model 'cheats' by looking into the future. This ruins production performance.\n- **The Solution:** The Feature Store API must perform an **AS OF Join** (Time-Travel Join). When constructing the training set, the offline store joins the label data with the feature data exactly as it existed immediately prior to the event timestamp, ignoring all newer rows.",
            complexity: "Complex"
        },
        {
            q: "Design an Enterprise RAG (Retrieval-Augmented Generation) pipeline that ingests 10 million unstructured PDFs daily into a Vector Database to power a chatbot. How do you handle document updates, deletions, and embedding model versioning?",
            a: "This is a specialized ELT pipeline designed for semantic search, heavily utilizing distributed processing to handle the massive compute required for embeddings.\n\n### 1. Ingestion & Change Data Tracking\n- **Event Triggers:** S3 object creation events or Confluence webhooks trigger an Airflow DAG or Kafka topic.\n- **Metadata State Table:** You must maintain a relational table (PostgreSQL) tracking `document_id`, `file_hash`, and `processing_status`. If a file is uploaded but its hash hasn't changed, the pipeline skips it, saving massive API costs.\n\n### 2. Processing (Chunking & Embedding)\n- **Engine:** Apache Spark (Databricks) or Ray.\n- **Chunking:** Unstructured text is extracted (via OCR/PyPDF) and split into semantic chunks (e.g., 512 tokens with a 50-token overlap). Overlaps prevent sentences from being cut in half, losing context.\n- **Embedding Generation:** Spark UDFs distribute API calls to the embedding model (e.g., OpenAI `text-embedding-3`). You must implement robust rate-limiting and exponential backoff to avoid HTTP 429 (Too Many Requests) errors.\n\n### 3. Managing Vector Database State (The 5 YOE Differentiator)\n- **Updates/Deletes:** Unlike relational databases, you cannot easily 'upsert' chunks if the chunk boundaries changed. If a PDF is updated, the pipeline must explicitly execute a `DELETE` query in the Vector DB (e.g., Milvus, Pinecone) using the metadata tag `document_id`, and then `INSERT` the newly generated chunks.\n- **Model Versioning:** If you upgrade your embedding model from v1 to v2, the dimensionality (e.g., 768 to 1536) and vector space completely change. You cannot mix them. You must create a *new collection* in the Vector DB, run a backfill batch job to re-embed all 10 million documents with v2, and then atomically hot-swap the chatbot's routing to the new collection.",
            complexity: "Complex"
        },
        {
            q: "You have a monolithic MySQL database handling millions of e-commerce orders. Complex analytical queries are degrading production performance. Design a real-time CDC pipeline to replicate this to a Lakehouse. How do you handle schema evolution and deduplication?",
            a: "A Change Data Capture (CDC) architecture decouples the analytical workload from the operational database with zero performance penalty.\n\n### 1. CDC Extraction\n- Deploy **Debezium**, which reads directly from MySQL's write-ahead log (`binlog`). Unlike JDBC polling (which executes `SELECT` statements and strains the DB), reading the binlog is virtually free. \n- Debezium translates every `INSERT`, `UPDATE`, and `DELETE` into an event payload and publishes it to Apache Kafka.\n\n### 2. Schema Evolution\n- Implement a **Schema Registry** (e.g., Confluent). \n- If a backend engineer runs an `ALTER TABLE` to add a new column in MySQL, Debezium detects the DDL change, registers the new Avro/Protobuf schema in the Registry, and the downstream consumers dynamically adapt to the new payload structure without breaking.\n\n### 3. Streaming Ingestion & Deduplication\n- **Engine:** Spark Structured Streaming or Flink consumes the Kafka topics.\n- **Lakehouse Merges:** Data is written to an **Apache Iceberg or Delta Lake** table. Because a single order might be updated 5 times in one minute (e.g., pending -> paid -> shipped), the streaming micro-batch must group by `order_id`, extract the row with the latest `updated_at` timestamp (or highest Kafka offset), and execute a `MERGE INTO` (Upsert) operation against the Lakehouse. This guarantees deduplication.\n\n### 4. Compaction (The Small Files Problem)\n- Real-time streaming creates thousands of tiny Parquet files on S3. Reading these is catastrophically slow due to I/O overhead.\n- **Solution:** Schedule an asynchronous background Airflow job to run `OPTIMIZE` and `ZORDER` (Delta Lake) or `RewriteDataFiles` (Iceberg). This compacts the tiny files into optimally sized ~1GB chunks, massively improving analytical read performance.",
            complexity: "Complex"
        },
        {
            q: "Design a customer-facing analytics API (Serving Layer) that allows thousands of merchants to query their live sales dashboards. The raw data is billions of rows in Snowflake, but the dashboard must load in <500ms and support custom filtering.",
            a: "Pointing a customer-facing API directly at a Data Warehouse (Snowflake/BigQuery) is a massive anti-pattern. They are designed for high-throughput, low-concurrency workloads and will suffer from queuing delays, high latency, and astronomical compute costs.\n\n### 1. The Pre-Aggregation Layer (Transformation)\n- Use **dbt** to build daily and hourly aggregate tables (e.g., `sales_by_merchant_day_product`) inside Snowflake. This reduces billions of raw rows down to millions of summarized rows.\n\n### 2. The Speed Layer (Real-Time OLAP)\n- Export the aggregated data from Snowflake and ingest it into a real-time analytical database engineered specifically for high-concurrency, sub-second latency. Standard choices are **Apache Druid, ClickHouse, or Apache Pinot**.\n- **Hybrid Ingestion:** \n  - *Historical Data:* Bulk-exported from Snowflake to S3, then loaded into ClickHouse.\n  - *Intra-day Data:* ClickHouse directly subscribes to the upstream Kafka sales topics, appending real-time events seamlessly alongside the historical batch data.\n\n### 3. The API Serving Layer\n- A lightweight Go or Node.js microservice receives the HTTP requests from the merchant dashboard.\n- It translates the user's dashboard filters (Date, Region, Product) into a highly optimized ClickHouse SQL query.\n- **Caching:** Implement a **Redis** caching layer in front of the API. When a merchant logs in, the dashboard typically queries the exact same default view ('This Month's Sales'). Caching this payload with a 5-minute TTL intercepts 80% of database hits, driving latency down to <10ms and protecting the database from traffic spikes.",
            complexity: "Complex"
        }
    ]
};

// Check if category already exists, if so update it, otherwise push it.
const existingCategoryIndex = interviewCategories.findIndex(c => c.id === sysDesignCategory.id);
if (existingCategoryIndex >= 0) {
    interviewCategories[existingCategoryIndex] = sysDesignCategory;
} else {
    interviewCategories.push(sysDesignCategory);
}

const jsContent = `export const interviewCategories = ${JSON.stringify(interviewCategories, null, 4)};\n`;
fs.writeFileSync('./src/data/interviewData.js', jsContent, 'utf-8');
console.log("System Design questions successfully added.");
